name: Publish on GitHub Pages

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: чек кода
      uses: actions/checkout@v4

    - name: Отправка в гит
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.G_TOKEN }}
        publish_dir: ./ 
        destination_dir: ./${{ github.event.release.tag_name }} 
